### ISSUE TITLE
Métodos do exemplo que não deveriam ter retorno retornam valor assim mesmo

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/delegua#170]
```
classe Resposta {
    enviar(codigo) {
        isto.codigo = codigo
    }

    status(statusHttp) {
        isto.statusHttp = statusHttp
    }
}

var resp = Resposta();
escreva(resp.enviar("Ok").status(200))
```

Neste caso:

```
enviar(codigo) {
        isto.codigo = codigo
    }
```

"Ok" é retornado pelo Interpretador, e

```
    status(statusHttp) {
        isto.statusHttp = statusHttp
    }
```

`200` é retornado pelo Interpretador.

**Comment by leonelsanchesdasilva** [comment]
```TypeError: Cannot read properties of undefined (reading 'lexema')
    at Interpretador.visitarExpressaoDefinirValor (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:1008:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DefinirValor.aceitar (C:\Delegua\delegua\fontes\construtos\definir-valor.ts:28:16)
    at async Interpretador.avaliar (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:196:16)
    at async Interpretador.visitarDeclaracaoDeExpressao (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:559:16)
    at async Expressao.aceitar (C:\Delegua\delegua\fontes\declaracoes\expressao.ts:14:16)
    at async Interpretador.executar (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:1209:32)
    at async Interpretador.executarUltimoEscopo (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:1239:35)
    at async Interpretador.executarBloco (C:\Delegua\delegua\fontes\interpretador\interpretador.ts:817:42)
    at async DeleguaFuncao.chamar (C:\Delegua\delegua\fontes\estruturas\delegua-funcao.ts:64:35)
```

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Não entendi o problema aqui?

Ainda existe problema?

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Isso acontece em projetos com Líquido. Precisamos atualizar tudo por lá, basicamente.

**Comment by AntoniodeNardin** [comment]
class Resposta {
    constructor() {
        this.codigo = null;
        this.statusHttp = null;
    }

    enviar(codigo) {
        this.codigo = codigo;
        return this; // Retornar a instância para permitir chamadas encadeadas
    }

    status(statusHttp) {
        this.statusHttp = statusHttp;
        return this; // Retornar a instância para permitir chamadas encadeadas
    }
}

var resp = new Resposta(); // Utilize 'new' para criar uma nova instância da classe
resp.enviar("Ok").status(200);
console.log(resp.codigo, resp.statusHttp);

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva 

Depois das atualizações de `liquido` podemos fechar essa ISSUE? 
Pode validar se esse problema ainda existe?

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Problema ainda persistir, reabrimos a ISSUE.
