### ISSUE TITLE
[VisuAlg] Método não implementado: `visitarExpressaoAcessoIndiceVariavel`

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/delegua#634]
Código:

```portugol
algoritmo "negativos"

var

  n, i: inteiro
  vet: vetor [0..9] de inteiro
    
inicio

  escreval("Quantos numeros voce vai digitar? ")
  leia(n)

  para i de 0 ate n-1 faca
    escreval("Digite um numero: ")
    leia(vet[i])
  fimpara

  escreval(" ")
  escreval("NUMEROS NEGATIVOS")

   para i de 0 ate n-1 faca
    se (vet[i] < 0) entao
      escreval(vet[i])
     fimse
  fimpara

fimalgoritmo
```

Erro do debug console:

```
Erro: Método não implementado.
at FormatadorVisuAlg.visitarExpressaoAcessoIndiceVariavel (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:297:15)
	at FormatadorVisuAlg.formatarDeclaracaoOuConstruto (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:539:22)
	at FormatadorVisuAlg.visitarExpressaoLeia (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:429:18)
	at FormatadorVisuAlg.formatarDeclaracaoOuConstruto (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:626:22)
	at FormatadorVisuAlg.formatarBlocoOuVetorDeclaracoes (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:362:18)
	at FormatadorVisuAlg.visitarDeclaracaoPara (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:232:14)
	at FormatadorVisuAlg.formatarDeclaracaoOuConstruto (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:635:22)
	at FormatadorVisuAlg.formatar (d:\Delegua\delegua\fontes\formatadores\formatador-visualg.ts:701:18)
	at VisualgProvedorFormatacao.provideDocumentFormattingEdits (d:\Delegua\vscode\fontes\formatadores\visualg-provedor-formatacao.ts:19:42)
	at z.provideDocumentFormattingEdits (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:93879)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:117930
	at pe.s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:112365)
	at pe.$provideDocumentFormattingEdits (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:117917)
	at d.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5520)
	at d.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5286)
	at d.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:4338)
	at d.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:3455)
	at g.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:2242)
	at r.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
	at g.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:8051)
	at r.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:6331)
	at MessagePortMain.emit (D:\Delegua\vscode\lib\events.js:514:28)
	at Object.emit (D:\Delegua\vscode\lib\electron\js2c\utility_init.js:2:2285)
	at Object.callbackTrampoline (node:internal/async_hooks:130:17) {stack: 'Error: Método não implementado.
	at Formatado…Trampoline (node:internal/async_hooks:130:17)', message: 'Método não implementado.'}
```

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/delegua/pull/635.
