### ISSUE TITLE
Erro ao iniciar RELP (Delégua)

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#91]
> C:\delegua\fontes\interpretador\pilha-escopos-execucao.ts:34     
>         this.pilha.at(-1).ambiente.valores[nomeVariavel] = valor;
>                    ^
> TypeError: this.pilha.at is not a function
>     at PilhaEscoposExecucao.definirVariavel (C:\delegua\fontes\interpretador\pilha-escopos-execucao.ts:34:20)
>     at default_1 (C:\delegua\fontes\bibliotecas\biblioteca-global.ts:12:26)
>     at new Interpretador (C:\delegua\fontes\interpretador\interpretador.ts:89:33)
>     at new Delegua (C:\delegua\fontes\delegua.ts:85:38)
>     at principal (C:\delegua\index.ts:21:21)
>     at Object.<anonymous> (C:\delegua\index.ts:30:1)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Module._compile (C:\delegua\node_modules\ts-node\src\index.ts:1455:23)
>     at internal/modules/cjs/loader.js:1114:10
>     at Object..ts (C:\delegua\node_modules\ts-node\src\index.ts:1458:12)
> Waiting for the debugger to disconnect...

**Comment by samuelrvg** [comment]
https://github.com/DesignLiquido/delegua/pull/92
